@baseUrl = http://localhost:4000

POST {{baseUrl}}/register
Content-Type: application/json

{
  "user_name":"burak4",
  "user_password":"burak3333"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
  "user_name":"burak4",
  "user_password":"burak3333"
}